local try_use = require('packer_bootstrap').try_use
try_use 'cespare/vim-toml'
try_use 'cstrahan/vim-capnp'
try_use 'dag/vim-fish'
try_use 'dcharbon/vim-flatbuffers'
try_use 'djpohly/vim-execline'
try_use 'gluon-lang/vim-gluon'
try_use 'jonsmithers/vim-html-template-literals'
try_use 'leafgarland/typescript-vim'
try_use 'pangloss/vim-javascript'
try_use 'tbastos/vim-lua'
try_use 'teal-language/vim-teal'
try_use 'andys8/vim-elm-syntax'
